import * as LucideIcons from "lucide-react";

import {
  LucideIcon,
  MoveRight as RightArrowIcon,
  MoveLeft as LeftArrowIcon,
  ChevronRight as RightIcon,
  ChevronLeft as LeftIcon,
  Eye as ShowIcon,
  EyeClosed as HideIcon,
  Loader as LoadingIcon,
  Aperture as CameraIcon,
  Crop as CropIcon,
  Trash as RemoveIcon,
  X as CloseIcon,
  CheckCheck as ProceedIcon,
  Save as SaveIcon,
  Expand as FullScreenIcon,
  Minimize as SmallScreenIcon,
  Eye as EyeIcon,
  GripHorizontal as GripIcon,
  Eye as PreviewIcon,
  Pencil as EditIcon,
  RotateCcw as ResetIcon,
  Monitor as DesktopIcon,
  Smartphone as MobileIcon,
  Image as ImageIcon,
  Plus as AddIcon,
  Minus as MinusIcon,
  Trash as TrashIcon,
  Layers as NavigatorIcon,
  Rows2 as RowIcon,
  Columns2 as ColumnIcon,
  Heading1 as H1Icon,
  Heading2 as H2Icon,
  Heading3 as H3Icon,
  Heading4 as H4Icon,
  Heading5 as H5Icon,
  Heading6 as H6Icon,
  Pilcrow as ParagraphIcon,
  MousePointerClick as SelectIcon,
  Code as CodeIcon,
  Minus as DividerIcon,
  List as ListIcon,
  Table as TableIcon,
  TextQuote as BlockquoteIcon,
  ListCollapse as AccordionIcon,
  ChevronsDownUp as CollapseIcon,
  AlignVerticalSpaceAround as SpacerIcon,
  SquarePlus as ButtonIcon,
  Trash as DeleteIcon,
  Copy as DuplicateIcon,
  X as ClearIcon,
  MoveLeft as MovePrevIcon,
  MoveRight as MoveNextIcon,
  AlignStartVertical as LeftAlignIcon,
  AlignEndVertical as RightAlignIcon,
  AlignCenterVertical as CenterAlignIcon,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  PilcrowRight as LRTIcon,
  PilcrowLeft as RTLIcon,
  ALargeSmall as CapitalizeIcon,
  CaseUpper as UppercaseIcon,
  CaseLower as LowercaseIcon,
  GripVertical as ResizeIcon,
  Share2 as ShareIcon,
  Bold as BoldIcon,
  Italic as ItalicIcon,
  Underline as UnderlineIcon,
  Strikethrough as StrikeIcon,
  Superscript as SupIcon,
  Subscript as SubIcon,
  Search as SearchIcon,
  Ellipsis as ThreeDotIcon,
  SkipForward as SkipIcon,
  EllipsisVertical as ThreeVerticalDotIcon,
  CornerDownRight as EnterIcon,
  Eye as ViewIcon,
  Pause as PauseIcon,
  Settings as SettingIcon,
  BellOff as NotificationOffIcon,
  ArrowDownToLine as DownloadIcon,
  ClockIcon,
  Boxes as CategoryListIcon,
  Flag as ReportIcon,
  ArrowUpToLine as UpIcon,
  ArrowDownToLine as DownIcon,
  MousePointerClick as ChangeReactionIcon,
  Link as LinkIcon,
  MessageSquareText as CommentIcon,
  ThumbsUp as LikeIcon,
  CheckCheck as CheckIcon,
  CheckCheck as CheckCheckIcon,
  Menu as MenuIcon,
  Bookmark as BookmarkIcon,
  AppWindowMac as AboutUsIcon,
  House as HomeIcon,
  TvMinimalPlay as ChannelIcon,
  CircleAlert as AlertIcon,
  SquarePen,
  LogOut as LogOutIcon,
  Sun as LightIcon,
  Moon as DarkIcon,
  Palette as ThemeIcon,
  MonitorCog as SystemIcon,
  Bell as NotificationIcon,
  ArrowLeft as LeftArrow2Icon,
  ArrowRight as RightArrow2Icon,
  ExternalLink,
  AlignCenterHorizontal as AlignCenterHorizontalIcon,
  AlignEndHorizontal as AlignEndHorizontalIcon,
  AlignStartHorizontal as AlignStartHorizontalIcon,
  AlignCenterVertical as AlignCenterVerticalIcon,
  AlignEndVertical as AlignEndVerticalIcon,
  AlignStartVertical as AlignStartVerticalIcon,
  AlignVerticalSpaceBetween as AlignVerticalSpaceBetweenIcon,
  AlignVerticalSpaceAround as AlignVerticalSpaceAroundIcon,
  AlignVerticalDistributeCenter as AlignVerticalDistributeCenterIcon,
  GalleryThumbnails as PostBannerIcon,
} from "lucide-react";

export {
  RightIcon,
  ShowIcon,
  HideIcon,
  LoadingIcon,
  CameraIcon,
  CropIcon,
  EditIcon,
  RemoveIcon,
  CloseIcon,
  ProceedIcon,
  LeftIcon,
  SaveIcon,
  FullScreenIcon,
  SmallScreenIcon,
  EyeIcon,
  GripIcon,
  PreviewIcon,
  ResetIcon,
  MobileIcon,
  DesktopIcon,
  ImageIcon,
  AddIcon,
  MinusIcon,
  TrashIcon,
  NavigatorIcon,
  RowIcon,
  ColumnIcon,
  H1Icon,
  H2Icon,
  H3Icon,
  H4Icon,
  H5Icon,
  H6Icon,
  ParagraphIcon,
  SelectIcon,
  CodeIcon,
  DividerIcon,
  ListIcon,
  TableIcon,
  BlockquoteIcon,
  AccordionIcon,
  CollapseIcon,
  SpacerIcon,
  ButtonIcon,
  DeleteIcon,
  DuplicateIcon,
  ClearIcon,
  MovePrevIcon,
  MoveNextIcon,
  LeftAlignIcon,
  RightAlignIcon,
  CenterAlignIcon,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  LRTIcon,
  RTLIcon,
  CapitalizeIcon,
  UppercaseIcon,
  LowercaseIcon,
  ResizeIcon,
  ShareIcon,
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  StrikeIcon,
  SupIcon,
  SubIcon,
  SearchIcon,
  ThreeDotIcon,
  SkipIcon,
  ThreeVerticalDotIcon,
  EnterIcon,
  ViewIcon,
  PauseIcon,
  SettingIcon,
  NotificationOffIcon,
  DownloadIcon,
  ClockIcon,
  CategoryListIcon,
  ReportIcon,
  UpIcon,
  DownIcon,
  ChangeReactionIcon,
  LinkIcon,
  CommentIcon,
  LikeIcon,
  CheckIcon,
  CheckCheckIcon,
  MenuIcon,
  BookmarkIcon,
  AboutUsIcon,
  HomeIcon,
  ChannelIcon,
  AlertIcon,
  SquarePen,
  LogOutIcon,
  LightIcon,
  DarkIcon,
  ThemeIcon,
  SystemIcon,
  NotificationIcon,
  LeftArrowIcon,
  RightArrowIcon,
  LeftArrow2Icon,
  RightArrow2Icon,
  ExternalLink,
  AlignCenterHorizontalIcon,
  AlignEndHorizontalIcon,
  AlignStartHorizontalIcon,
  AlignCenterVerticalIcon,
  AlignEndVerticalIcon,
  AlignStartVerticalIcon,
  AlignVerticalSpaceBetweenIcon,
  AlignVerticalSpaceAroundIcon,
  AlignVerticalDistributeCenterIcon,
  PostBannerIcon,
};

export type { LucideIcon };
export default LucideIcons;
