import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { MainScrollArea } from "@/components/scrollArea/MainScrollArea";

const openSans = Open_Sans({
  variable: "--font-open_sans",
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["italic", "normal"],
  subsets: ["latin", "greek"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased overflow-x-hidden font-[--font-open_sans]`}
        style={{
          fontFamily: "var(--font-open_sans)",
        }}
      >
        <MainScrollArea className="h-screen">{children}</MainScrollArea>
      </body>
    </html>
  );
};

export default RootLayout;
